### ISSUE TITLE
dth 몇개와 smartapp이 설치가 안됩니다.

### ISSUE THREAD

**Issue by sangkooki** [fison67/mi_connector#2]
먼저 감사말씀드립니다. ^^

github로 st에 설치시

dth의 반은 설치가 되고 반은 에러로 설치가 안됩니다.

<img width="602" alt="2018-03-24 11 33 52" src="https://user-images.githubusercontent.com/27760318/37859476-98a47e56-2f57-11e8-9641-4d53a9d4209b.png">

smartapp도 역시 github 설치가 안되고 있습니다.

<img width="841" alt="2018-03-24 11 38 48" src="https://user-images.githubusercontent.com/27760318/37859503-faca59f2-2f57-11e8-971f-71a229952971.png">

**Comment by OhJungTae** [comment]
오잉..저한테 보내시는 메일이 맞나요?

아기나무님이 깃허브에 올리신 스마트앱 코드를 복사해서 스마트싱스 ide 스마트앱스에서 코드추가로 설치하시면 됩니다.



나의 iPhone에서 보냄

2018. 3. 24. 오전 11:38, sangkooki <notifications@github.com> 작성:

**Comment by fison67** [comment]
파일 이름이 DTH, 스마트앱과 동일해야 되는 것 같아서 변경했습니다.

**Comment by OhJungTae** [comment]
이해가 잘 안되는데요,

아기나무집님이 깃허브에 올린 그루비 파일을 그냥 복사 후 붙여넣기 하시면 됩니다.
-----Original Message-----

**Comment by sangkooki** [comment]
감사합니다. smoke detector만 빼고 잘 설치되었습니다.
수동설치말고 github통합설치를 문의 드렸습니다.

**Comment by OhJungTae** [comment]
혹시 신짱님 깃허브에서 update from repo로 할 때 안되는게 있었다는 말씀이신가요?
-----Original Message-----
