### ISSUE TITLE
zhimi.airpurifier.m1 No control over device.

### ISSUE THREAD

**Issue by faGH** [fison67/mi_connector#27]
I believe this device is not officially supported as per your readme however It adds to ST fine and I can instantly monitor changes using ST DTH. However I can't seem to control the device :( None of the buttons perform any action.

Any idea when this support would be added? Many of my friends and I would very grateful.

**Comment by fison67** [comment]
Just remove zhimi.airpurifier.m1 on ST.
It will be added automatically soon.

That caused by the wrong server address of smart app.

If you  put the wrong address, remove all devices on ST.
Even if you change the server address, each device doesn't update server address inside.
