### ISSUE TITLE
No token found installing the latest version

### ISSUE THREAD

**Issue by barabba9174** [fison67/mi_connector#29]
Hi, I've an issue with my zhimi.airpurifier.m1: now the type is undefined, so I receive ad error: Control >> Error!!! TypeError: Cannot read property 'target' of undefined at /usr/src/app/routes/control.js:12:54

I'm using Raspberry Pi, so the error is on mi-connector-arm
Before the update everything worked fine, is it possibile to fix?

Thank you

Actual version log (I've tried also with the :latest)
Mi Connector Version >> 0.0.3.14
Finded >> But Mi-Connector can't get token from this device!!! id(47119176)
Find Device Manually but nothing token!!! >> 47119176

Old version log:
Finded >> WiFi  :zhimi.airpurifier.m1 Addrress=192.168.1.4 ID=47119176, Token=6d1e63eec$
Initialize WiFi Device >> zhimi.airpurifier.m1(47119176) ip=192.168.1.4

**Comment by fison67** [comment]
latest version is not latest.
Use a fison67/mi-connector-arm:test version.

I have no idea exactly but if mi connector doesn't find a token,
you must register a device manually with token & IP.

miio is not always able to find token.

Or remove a device from mi home and then add again.
