### ISSUE TITLE
gateway만 발견이 안됩니다

### ISSUE THREAD

**Issue by sangkooki** [fison67/mi_connector#3]
홈브릿지나 ha에서 잘 작동중인 게이트웨이가 mi coneector에서 자동발견이 안됩니다. wifi plug는 잘나오고 있습니다. lumi-gateway-v3 입니다.

**Comment by fison67** [comment]
안되면 수동 등록해보세요.
주소, 토큰 넣으셔서요.

메뉴 -> 장비 관리 -> 장비 목록 -> 추가

**Comment by sangkooki** [comment]
네 감사합니다
