### ISSUE TITLE
Get Data from ST is failed....

### ISSUE THREAD

**Issue by T-REX-XP** [fison67/mi_connector#33]
After registration device handler and smart app in samsung cloud(steps from manual), i can't connect to Samsund cloud via mi-connector

always receive following message in log:
Get Data from ST is failed....

Lumi gateway has been successfully found and child devices are found too.
But still cant connect to samsung cloud((

Works on synology docker.

**Comment by fison67** [comment]
Cuz Your ST App token or app id, app url is wrong.
