### ISSUE TITLE
Problem about Air Purifier and Light

### ISSUE THREAD

**Issue by bubykung** [fison67/mi_connector#36]
1. After open Mi air purifier 2 for a while. It always show status to off while still open

2. Please add update for Yeelight ceiling 5

3. Cannot access some xiaomi light page in new smartthings app

**Comment by fison67** [comment]
1. What do you mean? 
    While turning on air purifier, status is off?
    It's normal.
2. Let me know model type what you see on mi connector web dashboard.
3. Can access light on prv app?

**Comment by bubykung** [comment]
1. I mean If I turn on air purifier , It show status on just for hours then it show off while it still open. It looks like mi connector sometimes close air purifier and then turn it on but not show status on in smartthings app (I hear the sound that air purifier turn off and on immediately) 
2. the model is yeelink.light.ceiling5
3. Yes , I can access every mi product in classic smartthings app but in new smartthings app some product cannot access not only light

Thank you

**Comment by fison67** [comment]
1.Check current status on the recently tab and ide. 

2. That model is already supported.

3. What is that model?

**Comment by bubykung** [comment]
1. In device log , it show switch off after open for about 1 hour 15 minutes. it show Air Purifier mode is off and then Air Purifier switch is off. but My Air Purifier still running not off
2. In mi connector log , I have 2 device that show this after initialized mi connector
         warn | This yeelink.light.ceiling5 is not support now
         warn | This yeelink.light.strip2 is not support now
   So I think Mi connector found those devices but cannot initialized it
3. List of model that cannot access device page in new smartthings app , after access these devices it show white page : yeelink.light.color1 , yeelink.light.mono1 , philips.light.bulb , rockrobo.vacuum.v1 , zhimi.airpurifier.m1 , zhimi.airmonitor.v1 
   This is the only one model that I can access : yeelink.light.ceiling1

**Comment by fison67s** [comment]
1. I mean that I have to see full log...

2. Maybe you looks like a install a latest version.
   Install a test3 version.
    ex) fison67/mi-connector:test3

3. It's some different to set color on new app.
    I'm gonna update a DTH later

**Comment by fison67** [comment]
1. No, it's a just ST log...
    I have to see docker container log.
2. Yes, delete docker container first. And Install a test3 version.

**Comment by bubykung** [comment]
Does stable version will support yeelink.light.ceiling5 and yeelink.light.strip2 in the future ? 
If support,  I will wait for it.

**Comment by fison67** [comment]
Yes.
