### ISSUE TITLE
yeelink.light.ceiling3 and yeelink.light.ceiling4 are unupported?

### ISSUE THREAD

**Issue by mlc130104** [fison67/mi_connector#37]
![Capture](https://user-images.githubusercontent.com/7189975/56095592-fc636a80-5f10-11e9-9e47-ebf550e0e000.PNG)

**Comment by fison67** [comment]
What version did you install?
test3 version is current.

**Comment by mlc130104** [comment]
I installed latest as instructed in the manual.

**Comment by fison67** [comment]
Install a test3 version.
