### ISSUE TITLE
미커넥터 설치 후 동작 문제

### ISSUE THREAD

**Issue by acehan9301** [fison67/mi_connector#4]
DTH 및 스마트앱도 설치를 마쳤습니다.
큐냅 나스에 미커넥터 설치를 했는데.. 
로그상으로는 이슈가 없는 거 같은데 샤오미 기기를 가져오질 못합니다.
설정 페이지에서 테스트 버튼을 클릭할 경우 Error 가 발생하구요
해결할 방법이 있을까요?

**Comment by fison67** [comment]
나스와 동일한 호스트 사용 뭐 그런 옵션 없나요?
전체 포트를 다 사용해야 하는데...
30000번 포트 하나만 사용중인거면 안될겁니다.

테스트 버튼 에러는 ST App 과 연결이 제대로 되지 않는 것이구요

**Comment by fison67** [comment]
도커 실행되고 나서 ST 앱을 설치하면 자동으로 ST app_url 등을 넣을거에요.

근데 앱을 도커가 꺼져있을때 재설치 했다던지 뭐 여러가지 이유로 app_url, id, token이 안맞으면 연결이 안되겠죠

**Comment by fison67** [comment]
https://qnap-dev.github.io/container-station-api/qnet.html

여기 보면 네트워크 설정 부분에 네트워크 모드가 있네요.
거기서 설정하면 될 것 같은데요

**Comment by acehan9301** [comment]
브릿지로 선택해서 1번 랜포트를 지정하여 가상스위치를 만들었는데.. 
공기청정기 정보를 가져오긴 하는데.. ST 클래식 에서 온오프 동작이 되지 않고
매니지먼트 페이지도 열리지 않네요...

**Comment by fison67** [comment]
아마도 브릿지를 하면  IP 가 달라져서 안될거에요.
브릿지 말고 다른 모드 없나요?

**Comment by acehan9301** [comment]
NAT 와 Host 가 더 있어요.. 
사실 3가지 모두 해봤고.. 정상적으로 동작하지 않았어요.. 
매니지먼트 페이지에 접속이 되면 기기 정보를 가져오거나 ST 앱과 연동이 되지 않고, 
공기청정기 정보를 가져오면 온/오픈 동작이 안되면서 매니지먼트 페이지에 접속이 안되는 상황이 지속되고 있네요

**Comment by fison67** [comment]
어떤 모드를 했을때 나스와 동일한 아이피 대역으로 설정되나요?
Ex) 192.168.1.10, 192.168.1.11 이런식이요.

동일한 아이피 대역이 되면 그 주소로 매니지먼트 접속해보세요.  St 에서도 그 주소 넣어주고요

**Comment by fison67** [comment]
Host일 경우에는 어떤가요?
매니지먼트 접속되고 기기 정보 못가져오나요?
매니지먼트 접속안되고 기기 정보 가져오나요?

**Comment by acehan9301** [comment]
NAT로 했을 때 기존 IP로 접속이 가능했습니다.
그런데 기기정보도 못 불러오고, ST앱에서 매니지먼트가 아무것도 안뜨는 상황이 벌어졌죠

**Comment by fison67** [comment]
음 그러면 사용포트를 지정하는데
30000, 30001, 54321 번 포트 지정해서 컨테이너에서 사용가능하게 해서 해보실래요?
