### ISSUE TITLE
chuangmi.plug.hmi205 unsupported device

### ISSUE THREAD

**Issue by ytwytw** [fison67/mi_connector#44]
Hi I have a few mi plug USA version from Walmart USA

I have the token and when I add the device into the system, it gives this error

According https://github.com/rytilahti/python-miio/issues/427 , this is same as other variant of chuangmi.plug

Could you add support for this model?

Thanks

**Comment by fison67** [comment]
Ok.
I will add that model on next version.

**Comment by LunkSnee** [comment]
Is this fixed? I'm still getting:
mi        | 2020-03-02 06:36:10 [info]: Register Device to ST >> id(92545575) type(chuangmi.plug.hmi205)
mi        | 2020-03-02 06:36:10 [warn]: ST Smartpapps does not support chuangmi.plug.hmi205 DTH!!!

**Comment by fison67** [comment]
Update a smartapp.
