### ISSUE TITLE
Xiaomi light strip 2

### ISSUE THREAD

**Issue by tom8005** [fison67/mi_connector#45]
Hi

Thanks for the great software!

I’m having issues with xiaomi mi light strip 2 (recognized as 192.168.1.221 | yeelink.light.strip2)
I managed that it got shown on smartthings as device, however any action is not reflected on the device. 

Any thoughts? thanks a lot

Best

Log:
Date | Type | Content
-- | -- | --
2019-10-26 15:06:53 | info | Succes to add to Smartthings >> yeelink.light.strip2(131687781)
2019-10-26 15:06:53 | info | Try to register device to ST >> id=131687781, type=yeelink.light.strip2 [1/1]
2019-10-26 13:55:02 | info | Succes to add to Smartthings >> yeelink.light.strip2(131687781)
![012B0B25-AF29-4710-A71C-52EBF78B1AF4](https://user-images.githubusercontent.com/37790819/67621909-bf0f5c00-f814-11e9-83b2-f31c98bf4789.png)
![9B59CED6-EB29-4CB1-B93F-554BFF4875BA](https://user-images.githubusercontent.com/37790819/67621910-bfa7f280-f814-11e9-8685-379d151af561.png)
![779E4A4C-F551-4C7C-BE6A-BB55D2136B5E](https://user-images.githubusercontent.com/37790819/67621911-bfa7f280-f814-11e9-8138-faa97ae9a294.png)
![E98FB343-55D6-4A8D-A493-C993AEB1705C](https://user-images.githubusercontent.com/37790819/67621912-bfa7f280-f814-11e9-92c1-924efbd99267.png)

**Comment by fison67** [comment]
Select a docker ip on setup page.
And try again.

**Comment by bubykung** [comment]
I have problem with light strip 2 , too.

Token is correct but show error like this "Error: Could not connect to device, handshake timeout"

**Comment by fison67** [comment]
I mean that web page.
