### ISSUE TITLE
ClearGrass air monitor (cgllc.airmonitor.s1) not discovered 

### ISSUE THREAD

**Issue by zalewskigrzegorz** [fison67/mi_connector#47]
I configure everything step by step the worst part was with getting a token from the device.
But finally, I don't see any new device in the smartthings app
The device is recognized and connected to Mi Connector:
![obraz](https://user-images.githubusercontent.com/12560152/70847045-ff2bac00-1e5f-11ea-8e87-43843c22d4f6.png)

Device handlers were added and published:
![obraz](https://user-images.githubusercontent.com/12560152/70847027-dc999300-1e5f-11ea-9bb2-7548d3b5116f.png)

Mi connect app was installed:
![obraz](https://user-images.githubusercontent.com/12560152/70847072-56318100-1e60-11ea-9b64-84c07614fe69.png)
![obraz](https://user-images.githubusercontent.com/12560152/70847079-647f9d00-1e60-11ea-83d2-721caa20a090.png)
How can I check what is wrong?

**Comment by bubykung** [comment]
your ip in server address was wrong

**Comment by zalewskigrzegorz** [comment]
OMG I'm stupid. Thanks mate.
