### ISSUE TITLE
Xiaomi Air Purifier 3

### ISSUE THREAD

**Issue by medrazd** [fison67/mi_connector#49]
Hi,
I have problem to add Xiaomi Air Purifier 3 (zhimi.airpurifier.mb3) to Mi Connector. Info from log:

Initialize Wi-Fi Device >>  Error  ip(192.168.0.240), token=(*************************) : Error:  Could not connect to device, handshake timeout

Has something changed in new Xiaomi API? There is no problem with Roborock S6 (roborock.vacuum.s6) which is also not on the supported devices list.

**Comment by cdemi** [comment]
Is the Air Purifier you on a separate network by any chance? I had this issue when the mi-connector server and air purifier were on separate VLANs the connection timed out. 

I solved it by moving the server to the same network as the Air Purifier

**Comment by medrazd** [comment]
This is the same VLAN. I reinstalled application and the device is recognized by app now, but there is info in log:

2019-12-17	21:31:04 | warn | This zhimi.airpurifier.mb3 is not supported now

:(

**Comment by fison67** [comment]
Re download a docker image 0.0.4 or latest & Update a smartapp.
Then try again.
