### ISSUE TITLE
멀티탭 3개 중 두개가 작동을 안하고 이런 로그를 뿌립니다

### ISSUE THREAD

**Issue by OhJungTae** [fison67/mi_connector#5]
Xiaomi Settings
Type	Content
error	Get Device State TypeError: deviceMap[id].target.state is not a function Error at Object.module.exports.getDeviceState (/usr/src/app/miio/miio.js:1026:60) at processDeviceStatus (/usr/src/app/routes/websocket.js:169:10) at WebSocket.<anonymous> (/usr/src/app/routes/websocket.js:43:9) at emitOne (events.js:116:13) at WebSocket.emit (events.js:211:7) at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:715:20) at emitOne (events.js:116:13) at Receiver.emit (events.js:211:7) at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:414:14) at Receiver.getData (/usr/src/app/node_modules/ws/lib/receiver.js:346:17)
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"on"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"on"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"on"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"on"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"on"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
info	Requested to control by ST >> rockrobo.vacuum.v1[{"id":"55508490","cmd":"charge"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"on"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}]
info	Requested to control by ST >> rockrobo.vacuum.v1[{"id":"55508490","cmd":"clean"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"off"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"on"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48704499","cmd":"power","data":"off"}]
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: device.matches is not a function
error	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}] Erorr: TypeError: Cannot read property 'indexOf' of undefined
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48734306","cmd":"power","data":"off"}]
info	Requested to control by ST >> zimi.powerstrip.v2[{"id":"48716311","cmd":"power","data":"off"}]
info	Initialize WiFi Device >> zimi.powerstrip.v2(48734306)
info	Initialize WiFi Device >> zimi.powerstrip.v2(48704499)
info

**Comment by fison67** [comment]
다 동일한 종류 멀티탭인가요?

**Comment by OhJungTae** [comment]
메일 보내드렸습니다^^

**Comment by fison67** [comment]
메일이 안왔어요..

**Comment by fison67** [comment]
이건 장비 찾고 난 후에 등록하기 전 상세 정보 요청을 하는데
그때 빨리 응답이 안오면 그냥 생략하고 등록을 해요.
그때 등록하는 부분에서 버그가 있었네요.
고치고 말씀드릴께요.

**Comment by OhJungTae** [comment]
넵 감사합니다. 도커 재시작하니 정상작동하네요^^
