### ISSUE TITLE
Is it possible that Roborock mode is changing Air Purifier mode?

### ISSUE THREAD

**Issue by cdemi** [fison67/mi_connector#50]
I am experiencing a very strange problem where Sir Purifier automatically changes mode from favorite to auto. 

I think I have narrowed it down that when the Roborock goes back to charge, for some reason it switches the mode of the air purifier. 

Do you think the SmartThings appnis doing something to change this? Or am I looking in the wrong place?

**Comment by fison67** [comment]
I have no idea.
Do you use a webcore or automation smartapp ?

**Comment by cdemi** [comment]
I use the SmartThings SmartApp but I do have webcore automations that start the Roborock when I leave home
