### ISSUE TITLE
lumi.ctrl_ln1.aq1 not supported

### ISSUE THREAD

**Issue by droliverlewis** [fison67/mi_connector#51]
Hi,

Found another device ID that is not supported in your docker image: lumi.ctrl_ln1.aq1

In /usr/src/app/node_modules/miio/lib/devices/gateway/subdevices.js the following entry needs to be added to the module.exports:

`63: require('./ctrl_ln1'),`

Kind Regards
- Oliver

**Comment by fison67** [comment]
Thank you!
I will add it on next version.
