### ISSUE TITLE
Mi Smart Plug EU Version WiFi

### ISSUE THREAD

**Issue by bjornand1** [fison67/mi_connector#53]
Hi, I wonder if this smart plug is supported? I can add it in the Mi Connector dashboard, but it ends up under Not Initialized Xiaomi Devices.

**Comment by fison67** [comment]
What is your correct model name?
ex) rockrobo.vacuum.v1

**Comment by bjornand1** [comment]
Hi, thanks for responding! But I am unsure where I find the model name?

**Comment by bjornand1** [comment]
OK, I think I found it, could it be this: Xiaomi ZNCZ05CM Eu Smart Socket?

**Comment by fison67** [comment]
If you add a device to mi connector with token,
you can see a model on dashboard wedpage

**Comment by bjornand1** [comment]
Hi, I can add it, but it still appears under "Not Initialized Xiaomi Devices"

**Comment by bjornand1** [comment]
By the way, the log shows this error message:

Initialize Wi-Fi Device >> Error ip(192.168.1.xx), token=(xx) : Error: Could not connect to device, handshake timeout

**Comment by fison67** [comment]
Maybe wrong ip address or token?

You can see a model name on db file.

**Comment by bjornand1** [comment]
Hmm, I have checked again and both seem correct.

**Comment by fison67** [comment]
Use a Cloud Analyzer on menu.
