### ISSUE TITLE
Can't get connector to run on a raspberry pi zero

### ISSUE THREAD

**Issue by rocket59** [fison67/mi_connector#61]
I can't get this running on a pi zero. 

Docker installs ok (I tried suggestions on the internet to downgrade docker but connector still won't run) so not sure if this is a docker issue or mi connector container issue as I'm not too familiar with docker. I can get it running on a pi 3 but I only need this to be in my IOT Vlan so can't justify the cost of a pi3/4 just for this app.

Any ideas?

**Comment by rocket59** [comment]
Update - the container keeps restarting and the logs show a segmentation fault.

@fison67 is it possible to get a container built for arm6? Alternatively a manual install version that does not require docker?

**Comment by fison67** [comment]
I didn't make a armv6 docker image.
Only support amd64, arm64, armv7.

If you want manual install, pull a files from docker container.
/usr/src/app

**Comment by rocket59** [comment]
Thanks - I used an arm7 device instead.
