### ISSUE TITLE
ESP32 Bluetooth

### ISSUE THREAD

**Issue by rotrials** [fison67/mi_connector#62]
Hello,

First, thanks for the great project. 
I'm trying to add some Bluetooth devices to my smart home.
I have the following sensor: 
![image](https://user-images.githubusercontent.com/5993868/101241902-e2d4ef00-3702-11eb-822a-4d756939b3bf.png)
The mi connector is showing me that I have connect a ble.temperature, I got an ID. 
On the ESP32 board, I see that the sensor is sending temperature and humidity, but I cannot make it work on smartthings hub. Which dth do you use? How do you add it? 

Let me know if you need other information. Thanks

**Comment by fison67** [comment]
Xiaomi Bluetooth Weather DTH.
If you install a dth, it will be added automatically when docker restart.

**Comment by rotrials** [comment]
DTH was added, server restarted. I spend a couple of days and I was not able to make it work. The mi connector was shutdown and replaced by other solution. Unfortunately I cannot give further details...

**Comment by fison67** [comment]
Thanks.
