### ISSUE TITLE
Can't register new gateway

### ISSUE THREAD

**Issue by waterydan** [fison67/mi_connector#66]
I've manually added my new gateway using IP address and token, but when registering device the checkbox is disabled. I'm using the new gateway: Mi Smart Home Hub (USB powered). Is it supported? 

Edit: this is the gateway I'm using - https://www.cnx-software.com/2020/01/02/xiaomi-smart-multi-mode-gateway-supports-zigbee-3-0-wifi-bluetooth-and-bluetooth-mesh/

**Comment by fison67** [comment]
Sorry, not support that gateway.
